# Site settings
title: Hi, I'm Felipe.
description: Felipe González' professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Felipe González
user_title: 
user_job_title: Data Scientist
email: felipe57 [at] utp.edu.co
twitter_username: godlipe57
github_username:  Felikin

exclude: ['package.json', 'src' , 'node_modules']
